# Generated by Django 3.2.5 on 2022-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_poster',
            field=models.ImageField(default='/static/images/down.jpg', upload_to=''),
        ),
    ]
