# Generated by Django 3.2.5 on 2022-05-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_poster',
            field=models.ImageField(default='/static/images/down.jpg', upload_to='images/'),
        ),
    ]
