# Generated by Django 3.2.5 on 2022-05-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('cms_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user_cms_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_account')),
            ],
        ),
    ]
