# Generated by Django 3.2.5 on 2022-05-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
