# Generated by Django 3.2.5 on 2022-05-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0002_rename_user_events_user_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_event',
            unique_together={('user_cms_id', 'EventName')},
        ),
    ]
