# Generated by Django 3.2.5 on 2022-05-20 15:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_event_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+920000000000', max_length=128, region=None),
        ),
    ]
