# Generated by Django 3.2.5 on 2022-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_account_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='password',
            field=models.CharField(default='zzzzz', max_length=200),
        ),
    ]
