# Generated by Django 3.2.5 on 2022-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_event_date_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_event',
            name='purchase_type',
            field=models.CharField(choices=[('B', 'Bought'), ('R', 'RESERVED')], default='B', max_length=200),
        ),
    ]
