# Generated by Django 3.2.5 on 2022-05-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_event_purchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_event',
            name='purchase_type',
            field=models.CharField(choices=[('B', 'Bought'), ('R', 'RESERVED')], max_length=200),
        ),
    ]
