# Generated by Django 3.2.5 on 2022-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_event_date_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_event',
            name='date_bought',
            field=models.DateTimeField(),
        ),
    ]
