# Generated by Django 3.2.5 on 2022-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('organizer', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_tickets', models.IntegerField()),
                ('tickets_sold', models.IntegerField()),
                ('tickets_left', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
            ],
        ),
    ]
